let types = {

	// DATASET => NEXRAD2
	'ALL': "Base Data",

	// DATASET => NEXRAD3
	'DAA' : 'Digital Accumulation Array(One Hour Precipitation total (256 levels) with Dual Pol. algorithm)',
	'DHR' : 'Digital Hybrid Scan Reflectivity',
	'DOD' : 'One Hour Precipitation Difference = DAA-N1P',
	'DPA' : 'Digital Precipitation Array',
	'DPR' : 'Instantaneous Precipitation Rate',
	'DSD' : 'Storm Total Precipitation Difference = DTA-DSP',
	'DSP' : 'Digital Storm Total Precipitation',
	'DTA' : 'Digital Storm Total Accumulation(Storm Total Precipitation total (256 levels) with Dual Pol. algorithm)',
	'DVL' : 'Digital Vertical Integrated Liquid',
	'EET' : 'Enhanced Echo Tops',
	'FTM' : 'Free Text Message',
	'GSM' : 'General Status Message',
	'HHC' : 'Hybrid Hydrometeor Classification',
	'N0C' : 'Correlation Coefficient (approx. elev. angle: 0.5 deg)',
	'N0H' : 'Hydrometeor Classification (approx. elev.: 0.5 deg)',
	'N0K' : 'Specific Differential Phase (approx. elev.: 0.5 deg)',
	'N0Q' : 'Digital Base Reflectivity (approx. elev. angle: 0.5 deg)',
	'N0R' : 'Base Reflectivity (approx. elev. angle: 0.5 deg)',
	'N0S' : 'Storm Relative Velocity (approx. elev. angle: 0.5 deg)',
	'N0V' : 'Base Velocity (approx. elev. angle: 0.5 deg)',
	'N0W' : 'Base Velocity',
	'N0X' : 'Differential Reflectivity (approx. elev. angle: 0.5 deg)',
	'N0Z' : 'Long Range Base Reflectivity (460 km.',
	'N1C' : 'Correlation Coefficient (approx. elev. angle: 1.5 deg)',
	'N1H' : 'Hydrometeor Classification (approx. elev.: 1.5 deg)',
	'N1K' : 'Specific Differential Phase (approx. elev.: 1.5 deg)',
	'N1P' : 'One Hour Precipitation Total',
	'N1Q' : 'Digital Base Reflectivity (approx. elev. angle: 1.5 deg)',
	'N1R' : 'Base Reflectivity (approx. elev. angle: 1.5 deg)',
	'N1S' : 'Storm Relative Velocity (approx. elev. angle: 1.5 deg)',
	'N1V' : 'Base Velocity (approx. elev. angle: 1.5 deg)',
	'N1X' : 'Differential Reflectivity (approx. elev. angle: 1.5 deg)',
	'N2C' : 'Correlation Coefficient (approx. elev. angle: 2.4 deg)',
	'N2H' : 'Hydrometeor Classification (approx. elev.: 2.4 deg)',
	'N2K' : 'Specific Differential Phase (approx. elev.: 2.4 deg)',
	'N2Q' : 'Digital Base Reflectivity (approx. elev. angle: 2.4 deg)',
	'N2R' : 'Base Reflectivity (approx. elev. angle: 2.4 deg)',
	'N2S' : 'Storm Relative Velocity (approx. elev. angle: 2.4 deg)',
	'N2V' : 'Base Velocity (approx. elev. angle: 2.4 deg)',
	'N2X' : 'Differential Reflectivity (approx. elev. angle: 2.4 deg)',
	'N3C' : 'Correlation Coefficient (approx. elev. angle: 3.4 deg)',
	'N3H' : 'Hydrometeor Classification (approx. elev.: 3.4 deg)',
	'N3K' : 'Specific Differential Phase (approx. elev.: 3.4 deg)',
	'N3P' : 'Three Hour Precipitation Total',
	'N3Q' : 'Digital Base Reflectivity (approx. elev. angle: 3.4 deg)',
	'N3R' : 'Base Reflectivity (approx. elev. angle: 3.4 deg)',
	'N3S' : 'Storm Relative Velocity (approx. elev. angle: 3.4 deg)',
	'N3V' : 'Base Velocity (approx. elev. angle: 3.4 deg)',
	'N3X' : 'Differential Reflectivity (approx. elev. angle: 3.4 deg)',
	'NAC' : 'Correlation Coefficient (approx. elev. angle: 0.8 deg)',
	'NAH' : 'Hydrometeor Classification (approx. elev.: 0.8 deg)',
	'NAK' : 'Specific Differential Phase (approx. elev.: 0.8 deg)',
	'NAQ' : 'Digital Base Reflectivity (approx. elev. angle: 0.8 deg)',
	'NAX' : 'Differential Reflectivity (approx. elev. angle: 0.9 deg)',
	'NBC' : 'Correlation Coefficient (approx. elev. angle: 1.8 deg)',
	'NBH' : 'Hydrometeor Classification (approx. elev.: 1.8 deg)',
	'NBK' : 'Specific Differential Phase (approx. elev.: 1.8 deg)',
	'NBQ' : 'Digital Base Reflectivity (approx. elev. angle: 1.8 deg)',
	'NBX' : 'Differential Reflectivity (approx. elev. angle: 1.8 deg)',
	'NCR' : 'Composite Reflectivity (4x4 km. grid',
	'NCZ' : 'Composite Reflectivity (2x2 km. grid',
	'NET' : 'Echo Tops',
	'NHI' : 'Hail Index',
	'NHL' : 'High Layer Composite Reflectivity',
	'NLL' : 'Low Layer Composite Reflectivity',
	'NMD' : 'Digital Mesocyclone Detection Algorithm',
	'NME' : 'Mesocyclone',
	'NML' : 'Mid Layer Composite Reflectivity',
	'NSP' : 'Base Spectrum Width (60 km. range)',
	'NSS' : 'Storm Structure',
	'NST' : 'Storm Tracking Information',
	'NSW' : 'Base Spectrum Width (230 km. range)',
	'NTP' : 'Storm Total Precipitation',
	'NTV' : 'Tornadic Vortex Signature',
	'NVL' : 'Vertical Integrated Liquid',
	'OHA' : 'One Hour Accumulation(One Hour Precipitation total (16 levels) with Dual Pol. algorithm)',
	'PTA' : 'Storm Total Accumulation(Storm Total Precipitation total (16 levels) with Dual Pol. algorithm)',
	'RCM' : 'Radar Coded Message',
	'RSL' : 'WSR-88D Radar Status Log',
	'SPD' : 'Supplemental Precipitation Data',
	'TR0' : 'TDWR Base Reflectivity',
	'TR1' : 'TDWR Base Reflectivity',
	'TR2' : 'TDWR Base Reflectivity',
	'TV0' : 'TDWR Base Velocity (first elevation angle)',
	'TV1' : 'TDWR Base Velocity (second elevation angle)',
	'TV2' : 'TDWR Base Velocity (third elevation angle)',
	'TZL' : 'TDWR Long Range Base Reflectivity (0.6 elev angle)',

	
	// DATASET => GSOM
	'AWND' : 'Average wind speed',
	'CDSD' : 'Cooling Degree Days Season to Date',
	'CLDD' : 'Cooling Degree Days',
	'DP01' : 'Number of days with greater than or equal to 0.1 inch of precipitation',
	'DP05' : 'Number of days with greater than or equal to 0.5 inch of precipitation',
	'DP10' : 'Number of days with greater than or equal to 1.0 inch of precipitation',
	'DSND' : 'Number days with snow depth > 1 inch(25.4mm) for the period.',
	'DSNW' : 'Number days with snow depth > 1 inch.',
	'DT00' : 'Number days with minimum temperature less than or equal to 0.0 F',
	'DT32' : 'Number days with minimum temperature less than or equal to 32.0 F',
	'DX32' : 'Number days with maximum temperature < 32 F.',
	'DX70' : 'Number days with maximum temperature > 70 F (21.1C)',
	'DX90' : 'Number days with maximum temperature > 90 F (32.2C)',
	'EMNT' : 'Extreme minimum temperature for the period.',
	'EMSD' : 'Extreme maximum snow depth for the period.',
	'EMSN' : 'Extreme maximum snowfall for the period.',
	'EMXP' : 'Extreme maximum precipitation for the period.',
	'EMXT' : 'Extreme maximum temperature for the period.',
	'EVAP' : 'Evaporation of water from evaporation pan',
	'HDSD' : 'Heating Degree Days Season to Date',
	'HN01' : 'Highest minimum soil temperature for the month (degrees F)',
	'HN02' : 'Highest minimum soil temperature for the month (degrees F)',
	'HN03' : 'Highest minimum soil temperature for the month (degrees F)',
	'HN04' : 'Highest minimum soil temperature for the month (degrees F)',
	'HN05' : 'Highest minimum soil temperature for the month (degrees F)',
	'HN06' : 'Highest minimum soil temperature for the month (degrees F)',
	'HN07' : 'Highest minimum soil temperature for the month (degrees F)',
	'HN08' : 'Highest minimum soil temperature for the month (degrees F)',
	'HTDD' : 'Heating degree days',
	'HX01' : 'Highest maximum soil temperature for the month (degrees F)',
	'HX02' : 'Highest maximum soil temperature for the month (degrees F)',
	'HX03' : 'Highest maximum soil temperature for the month (degrees F)',
	'HX04' : 'Highest maximum soil temperature for the month (degrees F)',
	'HX05' : 'Highest maximum soil temperature for the month (degrees F)',
	'HX06' : 'Highest maximum soil temperature for the month (degrees F)',
	'HX07' : 'Highest maximum soil temperature for the month (degrees F)',
	'HX08' : 'Highest maximum soil temperature for the month (degrees F)',
	'LN01' : 'Lowest minimum soil temperature for the month (degrees F)',
	'LN02' : 'Lowest minimum soil temperature for the month (degrees F)',
	'LN03' : 'Lowest minimum soil temperature for the month (degrees F)',
	'LN04' : 'Lowest minimum soil temperature for the month (degrees F)',
	'LN05' : 'Lowest minimum soil temperature for the month (degrees F)',
	'LN06' : 'Lowest minimum soil temperature for the month (degrees F)',
	'LN07' : 'Lowest minimum soil temperature for the month (degrees F)',
	'LN08' : 'Lowest minimum soil temperature for the month (degrees F)',
	'LX01' : 'Lowest maximum soil temperature for the month (degrees F)',
	'LX02' : 'Lowest maximum soil temperature for the month (degrees F)',
	'LX03' : 'Lowest maximum soil temperature for the month (degrees F)',
	'LX04' : 'Lowest maximum soil temperature for the month (degrees F)',
	'LX05' : 'Lowest maximum soil temperature for the month (degrees F)',
	'LX06' : 'Lowest maximum soil temperature for the month (degrees F)',
	'LX07' : 'Lowest maximum soil temperature for the month (degrees F)',
	'LX08' : 'Lowest maximum soil temperature for the month (degrees F)',
	'MN01' : 'Monthly mean minimum soil temperature (degrees F)',
	'MN02' : 'Monthly mean minimum soil temperature (degrees F)',
	'MN03' : 'Monthly mean minimum soil temperature (degrees F)',
	'MN04' : 'Monthly mean minimum soil temperature (degrees F)',
	'MN05' : 'Monthly mean minimum soil temperature (degrees F)',
	'MN06' : 'Monthly mean minimum soil temperature (degrees F)',
	'MN07' : 'Monthly mean minimum soil temperature (degrees F)',
	'MN08' : 'Monthly mean minimum soil temperature (degrees F)',
	'MX01' : 'Monthly mean maximum soil temperature (degrees F)',
	'MX02' : 'Monthly mean maximum soil temperature (degrees F)',
	'MX03' : 'Monthly mean maximum soil temperature (degrees F)',
	'MX04' : 'Monthly mean maximum soil temperature (degrees F)',
	'MX05' : 'Monthly mean maximum soil temperature (degrees F)',
	'MX06' : 'Monthly mean maximum soil temperature (degrees F)',
	'MX07' : 'Monthly mean maximum soil temperature (degrees F)',
	'MX08' : 'Monthly mean maximum soil temperature (degrees F)',
	'PRCP' : 'Precipitation',
	'PSUN' : 'Daily percent of possible sunshine for the period',
	'SNOW' : 'Snowfall',
	'TAVG' : 'Average Temperature.',
	'TMAX' : 'Maximum temperature',
	'TMIN' : 'Minimum temperature',
	'TSUN' : 'Total sunshine for the period',
	'WDF1' : 'Direction of fastest 1-minute wind',
	'WDF2' : 'Direction of fastest 2-minute wind',
	'WDF5' : 'Direction of fastest 5-second wind',
	'WDFG' : 'Direction of peak wind gust',
	'WDFM' : 'Fastest mile wind direction',
	'WDMV' : 'Total wind movement',
	'WSF1' : 'Fastest 1-minute wind speed',
	'WSF2' : 'Fastest 2-minute wind speed',
	'WSF5' : 'Fastest 5-second wind speed',
	'WSFG' : 'Peak gust wind speed',
	'WSFM' : 'Fastest mile wind speed',


	// DATASET => GSOY
	// 'AWND' : 'Average wind speed',
	// 'CDSD' : 'Cooling Degree Days Season to Date',
	// 'CLDD' : 'Cooling Degree Days',
	// 'DP01' : 'Number of days with greater than or equal to 0.1 inch of precipitation',
	// 'DP05' : 'Number of days with greater than or equal to 0.5 inch of precipitation',
	// 'DP10' : 'Number of days with greater than or equal to 1.0 inch of precipitation',
	// 'DSND' : 'Number days with snow depth > 1 inch(25.4mm) for the period.',
	// 'DSNW' : 'Number days with snow depth > 1 inch.',
	// 'DT00' : 'Number days with minimum temperature less than or equal to 0.0 F',
	// 'DT32' : 'Number days with minimum temperature less than or equal to 32.0 F',
	// 'DX32' : 'Number days with maximum temperature < 32 F.',
	// 'DX70' : 'Number days with maximum temperature > 70 F (21.1C)',
	// 'DX90' : 'Number days with maximum temperature > 90 F (32.2C)',
	// 'EMNT' : 'Extreme minimum temperature for the period.',
	// 'EMSD' : 'Extreme maximum snow depth for the period.',
	// 'EMSN' : 'Extreme maximum snowfall for the period.',
	// 'EMXP' : 'Extreme maximum precipitation for the period.',
	// 'EMXT' : 'Extreme maximum temperature for the period.',
	// 'EVAP' : 'Evaporation of water from evaporation pan',
	'FZF0' : 'First freeze <= to 32F/0C of the year.',
	'FZF1' : 'First freeze <= 28F/-2.2C of the year',
	'FZF2' : 'First freeze <= 24F/-4.4C of the year',
	'FZF3' : 'First freeze <= 20F/-6.7C of the year',
	'FZF4' : 'First freeze <= 16F/-8.9C of the year',
	'FZF5' : 'Last freeze <= 32F/0C of the year',
	'FZF6' : 'Last freeze <= 28F/-2.2C of the year',
	'FZF7' : 'Last freeze <= 24F/-4.4C of the year',
	'FZF8' : 'Last freeze <= 20F/-6.7C of the year',
	'FZF9' : 'Last freeze <= 16F/-8.9C of the year',
	// 'HDSD' : 'Heating Degree Days Season to Date',
	// 'HTDD' : 'Heating degree days',
	// 'MN01' : 'Monthly mean minimum soil temperature (degrees F)',
	// 'MX01' : 'Monthly mean maximum soil temperature (degrees F)',
	// 'PRCP' : 'Precipitation',
	// 'PSUN' : 'Daily percent of possible sunshine for the period',
	// 'SNOW' : 'Snowfall',
	// 'TAVG' : 'Average Temperature.',
	// 'TMAX' : 'Maximum temperature',
	// 'TMIN' : 'Minimum temperature',
	// 'TSUN' : 'Total sunshine for the period',
	// 'WDF1' : 'Direction of fastest 1-minute wind',
	// 'WDF2' : 'Direction of fastest 2-minute wind',
	// 'WDF5' : 'Direction of fastest 5-second wind',
	// 'WDFG' : 'Direction of peak wind gust',
	// 'WDFM' : 'Fastest mile wind direction',
	// 'WDMV' : 'Total wind movement',
	// 'WSF1' : 'Fastest 1-minute wind speed',
	// 'WSF2' : 'Fastest 2-minute wind speed',
	// 'WSF5' : 'Fastest 5-second wind speed',
	// 'WSFG' : 'Peak gust wind speed',
	// 'WSFM' : 'Fastest mile wind speed',



	// DATASET => GHCND

	'ACMC' : 'Average cloudiness midnight to midnight from 30-second ceilometer data',
	'ACMH' : 'Average cloudiness midnight to midnight from manual observations',
	'ACSC' : 'Average cloudiness sunrise to sunset from 30-second ceilometer data',
	'ACSH' : 'Average cloudiness sunrise to sunset from manual observations',
	//'AWND' : 'Average wind speed',
	'DAEV' : 'Number of days included in the multiday evaporation total (MDEV)',
	'DAPR' : 'Number of days included in the multiday precipitation total (MDPR)',
	'DASF' : 'Number of days included in the multiday snow fall total (MDSF) ',
	'DATN' : 'Number of days included in the multiday minimum temperature (MDTN)',
	'DATX' : 'Number of days included in the multiday maximum temperature (MDTX)',
	'DAWM' : 'Number of days included in the multiday wind movement (MDWM)',
	'DWPR' : 'Number of days with non-zero precipitation included in multiday precipitation total (MDPR)',
	//'EVAP' : 'Evaporation of water from evaporation pan',
	'FMTM' : 'Time of fastest mile or fastest 1-minute wind',
	'FRGB' : 'Base of frozen ground layer',
	'FRGT' : 'Top of frozen ground layer',
	'FRTH' : 'Thickness of frozen ground layer',
	'GAHT' : 'Difference between river and gauge height',
	'MDEV' : 'Multiday evaporation total (use with DAEV)',
	'MDPR' : 'Multiday precipitation total (use with DAPR and DWPR, if available)',
	'MDSF' : 'Multiday snowfall total ',
	'MDTN' : 'Multiday minimum temperature (use with DATN)',
	'MDTX' : 'Multiday maximum temperature (use with DATX)',
	'MDWM' : 'Multiday wind movement',
	'MNPN' : 'Daily minimum temperature of water in an evaporation pan',
	'MXPN' : 'Daily maximum temperature of water in an evaporation pan',
	'PGTM' : 'Peak gust time',
	//'PRCP' : 'Precipitation',
	//'PSUN' : 'Daily percent of possible sunshine for the period',
	'SN01' : 'Minimum soil temperature with unknown cover at 5 cm depth',
	'SN02' : 'Minimum soil temperature with unknown cover at 10 cm depth',
	'SN03' : 'Minimum soil temperature with unknown cover at 20 cm depth',
	'SN11' : 'Minimum soil temperature with grass cover at 5 cm depth',
	'SN12' : 'Minimum soil temperature with grass cover at 10 cm depth',
	'SN13' : 'Minimum soil temperature with grass cover at 20 cm depth',
	'SN14' : 'Minimum soil temperature with grass cover at 50 cm depth',
	'SN21' : 'Minimum soil temperature with fallow cover at 5 cm depth',
	'SN22' : 'Minimum soil temperature with fallow cover at 10 cm depth',
	'SN23' : 'Minimum soil temperature with fallow cover at 20 cm depth',
	'SN31' : 'Minimum soil temperature with bare ground cover at 5 cm depth',
	'SN32' : 'Minimum soil temperature with bare ground cover at 10 cm depth',
	'SN33' : 'Minimum soil temperature with bare ground cover at 20 cm depth',
	'SN34' : 'Minimum soil temperature with bare ground cover at 50 cm depth',
	'SN35' : 'Minimum soil temperature with bare ground cover at 100 cm depth',
	'SN36' : 'Minimum soil temperature with bare ground cover at 150 cm depth',
	'SN51' : 'Minimum soil temperature with sod cover at 5 cm depth',
	'SN52' : 'Minimum soil temperature with sod cover at 10 cm depth',
	'SN53' : 'Minimum soil temperature with sod cover at 20 cm depth',
	'SN54' : 'Minimum soil temperature with sod cover at 50 cm depth',
	'SN55' : 'Minimum soil temperature with sod cover at 100 cm depth',
	'SN56' : 'Minimum soil temperature with sod cover at 150 cm depth',
	'SN57' : 'Minimum soil temperature with sod cover at 180 cm depth',
	'SN61' : 'Minimum soil temperature with straw multch cover at 5 cm depth',
	'SN72' : 'Minimum soil temperature with grass muck cover at 10 cm depth',
	'SN81' : 'Minimum soil temperature with bare muck cover at 5 cm depth',
	'SN82' : 'Minimum soil temperature with bare muck cover at 10 cm depth',
	'SN83' : 'Minimum soil temperature with bare muck cover at 20 cm depth',
	//'SNOW' : 'Snowfall',
	'SNWD' : 'Snow depth',
	'SX01' : 'Maximum soil temperature with unknown cover at 5 cm depth',
	'SX02' : 'Maximum soil temperature with unknown cover at 10 cm depth',
	'SX03' : 'Maximum soil temperature with unknown cover at 20 cm depth',
	'SX11' : 'Maximum soil temperature with grass cover at 5 cm depth',
	'SX12' : 'Maximum soil temperature with grass cover at 10 cm depth',
	'SX13' : 'Maximum soil temperature with grass cover at 20 cm depth',
	'SX14' : 'Maximum soil temperature with grass cover at 50 cm depth',
	'SX15' : 'Maximum soil temperature with grass cover at 100 cm depth',
	'SX17' : 'Maximum soil temperature with grass cover at 180 cm depth',
	'SX21' : 'Maximum soil temperature with fallow cover at 5 cm depth',
	'SX22' : 'Maximum soil temperature with fallow cover at 10 cm depth',
	'SX23' : 'Maximum soil temperature with fallow cover at 20 cm depth',
	'SX31' : 'Maximum soil temperature with bare ground cover at 5 cm depth',
	'SX32' : 'Maximum soil temperature with bare ground cover at 10 cm depth',
	'SX33' : 'Maximum soil temperature with bare ground cover at 20 cm depth',
	'SX34' : 'Maximum soil temperature with bare ground cover at 50 cm depth',
	'SX35' : 'Maximum soil temperature with bare ground cover at 100 cm depth',
	'SX36' : 'Maximum soil temperature with bare ground cover at 150 cm depth',
	'SX51' : 'Maximum soil temperature with sod cover at 5 cm depth',
	'SX52' : 'Maximum soil temperature with sod cover at 10 cm depth',
	'SX53' : 'Maximum soil temperature with sod cover at 20 cm depth',
	'SX54' : 'Maximum soil temperature with sod cover at 50 cm depth',
	'SX55' : 'Maximum soil temperature with sod cover at 100 cm depth',
	'SX56' : 'Maximum soil temperature with sod cover at 150 cm depth',
	'SX57' : 'Maximum soil temperature with sod cover at 180 cm depth',
	'SX61' : 'Maximum soil temperature with straw multch cover at 5 cm depth',
	'SX72' : 'Maximum soil temperature with grass muck cover at 10 cm depth',
	'SX81' : 'Maximum soil temperature with bare muck cover at 5 cm depth',
	'SX82' : 'Maximum soil temperature with bare muck cover at 10 cm depth',
	'SX83' : 'Maximum soil temperature with bare muck cover at 20 cm depth',
	//'TAVG' : 'Average Temperature.',
	//'THIC' : 'Thickness of ice on water',
	//'TMAX' : 'Maximum temperature',
	//'TMIN' : 'Minimum temperature',
	'TOBS' : 'Temperature at the time of observation',
	// 'TSUN' : 'Total sunshine for the period',
	// 'WDF1' : 'Direction of fastest 1-minute wind',
	// 'WDF2' : 'Direction of fastest 2-minute wind',
	// 'WDF5' : 'Direction of fastest 5-second wind',
	// 'WDFG' : 'Direction of peak wind gust',
	// 'WDFI' : 'Direction of highest instantaneous wind',
	// 'WDFM' : 'Fastest mile wind direction',
	// 'WDMV' : 'Total wind movement',
	'WESD' : 'Water equivalent of snow on the ground',
	'WESF' : 'Water equivalent of snowfall',
	// 'WSF1' : 'Fastest 1-minute wind speed',
	// 'WSF2' : 'Fastest 2-minute wind speed',
	// 'WSF5' : 'Fastest 5-second wind speed',
	// 'WSFG' : 'Peak gust wind speed',
	'WSFI' : 'Highest instantaneous wind speed',
	//'WSFM' : 'Fastest mile wind speed',
	'WT01' : 'Fog, ice fog, or freezing fog (may include heavy fog)',
	'WT02' : 'Heavy fog or heaving freezing fog (not always distinguished from fog)',
	'WT03' : 'Thunder',
	'WT04' : 'Ice pellets, sleet, snow pellets, or small hail" ',
	'WT05' : 'Hail (may include small hail)',
	'WT06' : 'Glaze or rime ',
	'WT07' : 'Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction',
	'WT08' : 'Smoke or haze ',
	'WT09' : 'Blowing or drifting snow',
	'WT10' : 'Tornado, waterspout, or funnel cloud" ',
	'WT11' : 'High or damaging winds',
	'WT12' : 'Blowing spray',
	'WT13' : 'Mist',
	'WT14' : 'Drizzle',
	'WT15' : 'Freezing drizzle ',
	'WT16' : 'Rain (may include freezing rain, drizzle, and freezing drizzle)" ',
	'WT17' : 'Freezing rain ',
	'WT18' : 'Snow, snow pellets, snow grains, or ice crystals',
	'WT19' : 'Unknown source of precipitation ',
	'WT21' : 'Ground fog ',
	'WT22' : 'Ice fog or freezing fog',
	'WV01' : 'Fog, ice fog, or freezing fog (may include heavy fog)',
	'WV03' : 'Thunder',
	'WV07' : 'Ash, dust, sand, or other blowing obstruction',
	'WV18' : 'Snow or ice crystals',
	'WV20' : 'Rain or snow shower',


	// DATASET => NORMAL_ANN

	'ANN-CLDD-BASE45' : 'Long-term averages of annual cooling degree days with base 45F',
	'ANN-CLDD-BASE50' : 'Long-term averages of annual cooling degree days with base 50F',
	'ANN-CLDD-BASE55' : 'Long-term averages of annual cooling degree days with base 55F',
	'ANN-CLDD-BASE57' : 'Long-term averages of annual cooling degree days with base 57F',
	'ANN-CLDD-BASE60' : 'Long-term averages of annual cooling degree days with base 60F',
	'ANN-CLDD-BASE70' : 'Long-term averages of annual cooling degree days with base 70F',
	'ANN-CLDD-BASE72' : 'Long-term averages of annual cooling degree days with base 72F',
	'ANN-CLDD-NORMAL' : 'Long-term averages of annual cooling degree days with base 65F',
	'ANN-DUTR-NORMAL' : 'Long-term averages of annual diurnal temperature range',
	'ANN-GRDD-BASE40' : 'Long-term averages of annual growing degree days with base 40F',
	'ANN-GRDD-BASE45' : 'Long-term averages of annual growing degree days with base 45F',
	'ANN-GRDD-BASE50' : 'Long-term averages of annual growing degree days with base 50F',
	'ANN-GRDD-BASE55' : 'Long-term averages of annual growing degree days with base 55F',
	'ANN-GRDD-BASE57' : 'Long-term averages of annual growing degree days with base 57F',
	'ANN-GRDD-BASE60' : 'Long-term averages of annual growing degree days with base 60F',
	'ANN-GRDD-BASE65' : 'Long-term averages of annual growing degree days with base 65F',
	'ANN-GRDD-BASE70' : 'Long-term averages of annual growing degree days with base 70F',
	'ANN-GRDD-BASE72' : 'Long-term averages of annual growing degree days with base 72F',
	'ANN-GRDD-TB4886' : 'Long-term averages of annual growing degree days with truncated bases 48F and 86F',
	'ANN-GRDD-TB5086' : 'Long-term averages of annual growing degree days with truncated bases 50F and 86F',
	'ANN-HTDD-BASE40' : 'Long-term averages of annual heating degree days with base 40F',
	'ANN-HTDD-BASE45' : 'Long-term averages of annual heating degree days with base 45F',
	'ANN-HTDD-BASE50' : 'Long-term averages of annual heating degree days with base 50F',
	'ANN-HTDD-BASE55' : 'Long-term averages of annual heating degree days with base 55F',
	'ANN-HTDD-BASE57' : 'Long-term averages of annual heating degree days with base 57F',
	'ANN-HTDD-BASE60' : 'Long-term averages of annual heating degree days with base 60F',
	'ANN-HTDD-NORMAL' : 'Long-term averages of annual heating degree days with base 65F',
	'ANN-PRCP-AVGNDS-GE001HI' : 'Long-term averages of number of days during the year with precipitation >= 0.01 inches',
	'ANN-PRCP-AVGNDS-GE010HI' : 'Long-term averages of number of days during the year with precipitation >= 0.10 inches',
	'ANN-PRCP-AVGNDS-GE050HI' : 'Long-term averages of number of days during the year with precipitation >= 0.50 inches',
	'ANN-PRCP-AVGNDS-GE100HI' : 'Long-term averages of number of days during the year with precipitation >= 1.00 inches',
	'ANN-PRCP-NORMAL' : 'Long-term averages of annual precipitation totals',
	'ANN-SNOW-AVGNDS-GE001TI' : 'Long-term averages of number of days during the year with snowfall >= 0.1 inches',
	'ANN-SNOW-AVGNDS-GE010TI' : 'Long-term averages of number of days during the year with snowfall >= 1.0 inches',
	'ANN-SNOW-AVGNDS-GE030TI' : 'Long-term averages of number of days during the year with snowfall >= 3.0 inches',
	'ANN-SNOW-AVGNDS-GE050TI' : 'Long-term averages of number of days during the year with snowfall >= 5.0 inches',
	'ANN-SNOW-AVGNDS-GE100TI' : 'Long-term averages of number of days during the year with snowfall >= 10.0 inches',
	'ANN-SNOW-NORMAL' : 'Long-term averages of annual snowfall totals',
	'ANN-SNWD-AVGNDS-GE001WI' : 'Long-term averages of number of days during the year with snow depth >= 1 inch',
	'ANN-SNWD-AVGNDS-GE003WI' : 'Long-term averages of number of days during the year with snow depth >= 3 inches',
	'ANN-SNWD-AVGNDS-GE005WI' : 'Long-term averages of number of days during the year with snow depth >=5 inches',
	'ANN-SNWD-AVGNDS-GE010WI' : 'Long-term averages of number of days during the year with snow depth >=10 inches',
	'ANN-TAVG-NORMAL' : 'Long-term averages of annual average temperature',
	'ANN-TMAX-AVGNDS-GRTH040' : 'Long-term average number of days per year where tmax is greater than or equal to 40F',
	'ANN-TMAX-AVGNDS-GRTH050' : 'Long-term average number of days per year where tmax is greater than or equal to 50F',
	'ANN-TMAX-AVGNDS-GRTH060' : 'Long-term average number of days per year where tmax is greater than or equal to 60F',
	'ANN-TMAX-AVGNDS-GRTH070' : 'Long-term average number of days per year where tmax is greater than or equal to 70F',
	'ANN-TMAX-AVGNDS-GRTH080' : 'Long-term average number of days per year where tmax is greater than or equal to 80F',
	'ANN-TMAX-AVGNDS-GRTH090' : 'Long-term average number of days per year where tmax is greater than or equal to 90F',
	'ANN-TMAX-AVGNDS-GRTH100' : 'Long-term average number of days per year where tmax is greater than or equal to 100F',
	'ANN-TMAX-AVGNDS-LSTH032' : 'Long-term average number of days per year where tmax is less than or equal to 32F',
	'ANN-TMAX-NORMAL' : 'Long-term averages of annual maximum temperature',
	'ANN-TMIN-AVGNDS-LSTH000' : 'Long-term average number of days per year where tmin is less than or equal to 0F',
	'ANN-TMIN-AVGNDS-LSTH010' : 'Long-term average number of days per year where tmin is less than or equal to 10F',
	'ANN-TMIN-AVGNDS-LSTH020' : 'Long-term average number of days per year where tmin is less than or equal to 20F',
	'ANN-TMIN-AVGNDS-LSTH032' : 'Long-term average number of days per year where tmin is less than or equal to 32F',
	'ANN-TMIN-AVGNDS-LSTH040' : 'Long-term average number of days per year where tmin is less than or equal to 40F',
	'ANN-TMIN-AVGNDS-LSTH050' : 'Long-term average number of days per year where tmin is less than or equal to 50F',
	'ANN-TMIN-AVGNDS-LSTH060' : 'Long-term average number of days per year where tmin is less than or equal to 60F',
	'ANN-TMIN-AVGNDS-LSTH070' : 'Long-term average number of days per year where tmin is less than or equal to 70F',
	'ANN-TMIN-NORMAL' : 'Long-term averages of annual minimum temperature',
	'ANN-TMIN-PRBFST-T16FP10' : '10% probability date of first 16F occurrence or earlier',
	'ANN-TMIN-PRBFST-T16FP20' : '20% probability date of first 16F occurrence or earlier',
	'ANN-TMIN-PRBFST-T16FP30' : '30% probability date of first 16F occurrence or earlier',
	'ANN-TMIN-PRBFST-T16FP40' : '40% probability date of first 16F occurrence or earlier',
	'ANN-TMIN-PRBFST-T16FP50' : '50% probability date of first 16F occurrence or earlier',
	'ANN-TMIN-PRBFST-T16FP60' : '60% probability date of first 16F occurrence or earlier',
	'ANN-TMIN-PRBFST-T16FP70' : '70% probability date of first 16F occurrence or earlier',
	'ANN-TMIN-PRBFST-T16FP80' : '80% probability date of first 16F occurrence or earlier',
	'ANN-TMIN-PRBFST-T16FP90' : '90% probability date of first 16F occurrence or earlier',
	'ANN-TMIN-PRBFST-T20FP10' : '10% probability date of first 20F occurrence or earlier',
	'ANN-TMIN-PRBFST-T20FP20' : '20% probability date of first 20F occurrence or earlier',
	'ANN-TMIN-PRBFST-T20FP30' : '30% probability date of first 20F occurrence or earlier',
	'ANN-TMIN-PRBFST-T20FP40' : '40% probability date of first 20F occurrence or earlier',
	'ANN-TMIN-PRBFST-T20FP50' : '50% probability date of first 20F occurrence or earlier',
	'ANN-TMIN-PRBFST-T20FP60' : '60% probability date of first 20F occurrence or earlier',
	'ANN-TMIN-PRBFST-T20FP70' : '70% probability date of first 20F occurrence or earlier',
	'ANN-TMIN-PRBFST-T20FP80' : '80% probability date of first 20F occurrence or earlier',
	'ANN-TMIN-PRBFST-T20FP90' : '90% probability date of first 20F occurrence or earlier',
	'ANN-TMIN-PRBFST-T24FP10' : '10% probability date of first 24F occurrence or earlier',
	'ANN-TMIN-PRBFST-T24FP20' : '20% probability date of first 24F occurrence or earlier',
	'ANN-TMIN-PRBFST-T24FP30' : '30% probability date of first 24F occurrence or earlier',
	'ANN-TMIN-PRBFST-T24FP40' : '40% probability date of first 24F occurrence or earlier',
	'ANN-TMIN-PRBFST-T24FP50' : '50% probability date of first 24F occurrence or earlier',
	'ANN-TMIN-PRBFST-T24FP60' : '60% probability date of first 24F occurrence or earlier',
	'ANN-TMIN-PRBFST-T24FP70' : '70% probability date of first 24F occurrence or earlier',
	'ANN-TMIN-PRBFST-T24FP80' : '80% probability date of first 24F occurrence or earlier',
	'ANN-TMIN-PRBFST-T24FP90' : '90% probability date of first 24F occurrence or earlier',
	'ANN-TMIN-PRBFST-T28FP10' : '10% probability date of first 28F occurrence or earlier',
	'ANN-TMIN-PRBFST-T28FP20' : '20% probability date of first 28F occurrence or earlier',
	'ANN-TMIN-PRBFST-T28FP30' : '30% probability date of first 28F occurrence or earlier',
	'ANN-TMIN-PRBFST-T28FP40' : '40% probability date of first 28F occurrence or earlier',
	'ANN-TMIN-PRBFST-T28FP50' : '50% probability date of first 28F occurrence or earlier',
	'ANN-TMIN-PRBFST-T28FP60' : '60% probability date of first 28F occurrence or earlier',
	'ANN-TMIN-PRBFST-T28FP70' : '70% probability date of first 28F occurrence or earlier',
	'ANN-TMIN-PRBFST-T28FP80' : '80% probability date of first 28F occurrence or earlier',
	'ANN-TMIN-PRBFST-T28FP90' : '90% probability date of first 28F occurrence or earlier',
	'ANN-TMIN-PRBFST-T32FP10' : '10% probability date of first 32F occurrence or earlier',
	'ANN-TMIN-PRBFST-T32FP20' : '20% probability date of first 32F occurrence or earlier',
	'ANN-TMIN-PRBFST-T32FP30' : '30% probability date of first 32F occurrence or earlier',
	'ANN-TMIN-PRBFST-T32FP40' : '40% probability date of first 32F occurrence or earlier',
	'ANN-TMIN-PRBFST-T32FP50' : '50% probability date of first 32F occurrence or earlier',
	'ANN-TMIN-PRBFST-T32FP60' : '60% probability date of first 32F occurrence or earlier',
	'ANN-TMIN-PRBFST-T32FP70' : '70% probability date of first 32F occurrence or earlier',
	'ANN-TMIN-PRBFST-T32FP80' : '80% probability date of first 32F occurrence or earlier',
	'ANN-TMIN-PRBFST-T32FP90' : '90% probability date of first 32F occurrence or earlier',
	'ANN-TMIN-PRBFST-T36FP10' : '10% probability date of first 36F occurrence or earlier',
	'ANN-TMIN-PRBFST-T36FP20' : '20% probability date of first 36F occurrence or earlier',
	'ANN-TMIN-PRBFST-T36FP30' : '30% probability date of first 36F occurrence or earlier',
	'ANN-TMIN-PRBFST-T36FP40' : '40% probability date of first 36F occurrence or earlier',
	'ANN-TMIN-PRBFST-T36FP50' : '50% probability date of first 36F occurrence or earlier',
	'ANN-TMIN-PRBFST-T36FP60' : '60% probability date of first 36F occurrence or earlier',
	'ANN-TMIN-PRBFST-T36FP70' : '70% probability date of first 36F occurrence or earlier',
	'ANN-TMIN-PRBFST-T36FP80' : '80% probability date of first 36F occurrence or earlier',
	'ANN-TMIN-PRBFST-T36FP90' : '90% probability date of first 36F occurrence or earlier',
	'ANN-TMIN-PRBGSL-T16FP10' : '10% probability of 16F growing season length or longer',
	'ANN-TMIN-PRBGSL-T16FP20' : '20% probability of 16F growing season length or longer',
	'ANN-TMIN-PRBGSL-T16FP30' : '30% probability of 16F growing season length or longer',
	'ANN-TMIN-PRBGSL-T16FP40' : '40% probability of 16F growing season length or longer',
	'ANN-TMIN-PRBGSL-T16FP50' : '50% probability of 16F growing season length or longer',
	'ANN-TMIN-PRBGSL-T16FP60' : '60% probability of 16F growing season length or longer',
	'ANN-TMIN-PRBGSL-T16FP70' : '70% probability of 16F growing season length or longer',
	'ANN-TMIN-PRBGSL-T16FP80' : '80% probability of 16F growing season length or longer',
	'ANN-TMIN-PRBGSL-T16FP90' : '90% probability of 16F growing season length or longer',
	'ANN-TMIN-PRBGSL-T20FP10' : '10% probability of 20F growing season length or longer',
	'ANN-TMIN-PRBGSL-T20FP20' : '20% probability of 20F growing season length or longer',
	'ANN-TMIN-PRBGSL-T20FP30' : '30% probability of 20F growing season length or longer',
	'ANN-TMIN-PRBGSL-T20FP40' : '40% probability of 20F growing season length or longer',
	'ANN-TMIN-PRBGSL-T20FP50' : '50% probability of 20F growing season length or longer',
	'ANN-TMIN-PRBGSL-T20FP60' : '60% probability of 20F growing season length or longer',
	'ANN-TMIN-PRBGSL-T20FP70' : '70% probability of 20F growing season length or longer',
	'ANN-TMIN-PRBGSL-T20FP80' : '80% probability of 20F growing season length or longer',
	'ANN-TMIN-PRBGSL-T20FP90' : '90% probability of 20F growing season length or longer',
	'ANN-TMIN-PRBGSL-T24FP10' : '10% probability of 24F growing season length or longer',
	'ANN-TMIN-PRBGSL-T24FP20' : '20% probability of 24F growing season length or longer',
	'ANN-TMIN-PRBGSL-T24FP30' : '30% probability of 24F growing season length or longer',
	'ANN-TMIN-PRBGSL-T24FP40' : '40% probability of 24F growing season length or longer',
	'ANN-TMIN-PRBGSL-T24FP50' : '50% probability of 24F growing season length or longer',
	'ANN-TMIN-PRBGSL-T24FP60' : '60% probability of 24F growing season length or longer',
	'ANN-TMIN-PRBGSL-T24FP70' : '70% probability of 24F growing season length or longer',
	'ANN-TMIN-PRBGSL-T24FP80' : '80% probability of 24F growing season length or longer',
	'ANN-TMIN-PRBGSL-T24FP90' : '90% probability of 24F growing season length or longer',
	'ANN-TMIN-PRBGSL-T28FP10' : '10% probability of 28F growing season length or longer',
	'ANN-TMIN-PRBGSL-T28FP20' : '20% probability of 28F growing season length or longer',
	'ANN-TMIN-PRBGSL-T28FP30' : '30% probability of 28F growing season length or longer',
	'ANN-TMIN-PRBGSL-T28FP40' : '40% probability of 28F growing season length or longer',
	'ANN-TMIN-PRBGSL-T28FP50' : '50% probability of 28F growing season length or longer',
	'ANN-TMIN-PRBGSL-T28FP60' : '60% probability of 28F growing season length or longer',
	'ANN-TMIN-PRBGSL-T28FP70' : '70% probability of 28F growing season length or longer',
	'ANN-TMIN-PRBGSL-T28FP80' : '80% probability of 28F growing season length or longer',
	'ANN-TMIN-PRBGSL-T28FP90' : '90% probability of 28F growing season length or longer',
	'ANN-TMIN-PRBGSL-T32FP10' : '10% probability of 32F growing season length or longer',
	'ANN-TMIN-PRBGSL-T32FP20' : '20% probability of 32F growing season length or longer',
	'ANN-TMIN-PRBGSL-T32FP30' : '30% probability of 32F growing season length or longer',
	'ANN-TMIN-PRBGSL-T32FP40' : '40% probability of 32F growing season length or longer',
	'ANN-TMIN-PRBGSL-T32FP50' : '50% probability of 32F growing season length or longer',
	'ANN-TMIN-PRBGSL-T32FP60' : '60% probability of 32F growing season length or longer',
	'ANN-TMIN-PRBGSL-T32FP70' : '70% probability of 32F growing season length or longer',
	'ANN-TMIN-PRBGSL-T32FP80' : '80% probability of 32F growing season length or longer',
	'ANN-TMIN-PRBGSL-T32FP90' : '90% probability of 32F growing season length or longer',
	'ANN-TMIN-PRBGSL-T36FP10' : '10% probability of 36F growing season length or longer',
	'ANN-TMIN-PRBGSL-T36FP20' : '20% probability of 36F growing season length or longer',
	'ANN-TMIN-PRBGSL-T36FP30' : '30% probability of 36F growing season length or longer',
	'ANN-TMIN-PRBGSL-T36FP40' : '40% probability of 36F growing season length or longer',
	'ANN-TMIN-PRBGSL-T36FP50' : '50% probability of 36F growing season length or longer',
	'ANN-TMIN-PRBGSL-T36FP60' : '60% probability of 36F growing season length or longer',
	'ANN-TMIN-PRBGSL-T36FP70' : '70% probability of 36F growing season length or longer',
	'ANN-TMIN-PRBGSL-T36FP80' : '80% probability of 36F growing season length or longer',
	'ANN-TMIN-PRBGSL-T36FP90' : '90% probability of 36F growing season length or longer',
	'ANN-TMIN-PRBLST-T16FP10' : '10% probability date of last 16F occurrence or later',
	'ANN-TMIN-PRBLST-T16FP20' : '20% probability date of last 16F occurrence or later',
	'ANN-TMIN-PRBLST-T16FP30' : '30% probability date of last 16F occurrence or later',
	'ANN-TMIN-PRBLST-T16FP40' : '40% probability date of last 16F occurrence or later',
	'ANN-TMIN-PRBLST-T16FP50' : '50% probability date of last 16F occurrence or later',
	'ANN-TMIN-PRBLST-T16FP60' : '60% probability date of last 16F occurrence or later',
	'ANN-TMIN-PRBLST-T16FP70' : '70% probability date of last 16F occurrence or later',
	'ANN-TMIN-PRBLST-T16FP80' : '80% probability date of last 16F occurrence or later',
	'ANN-TMIN-PRBLST-T16FP90' : '90% probability date of last 16F occurrence or later',
	'ANN-TMIN-PRBLST-T20FP10' : '10% probability date of last 20F occurrence or later',
	'ANN-TMIN-PRBLST-T20FP20' : '20% probability date of last 20F occurrence or later',
	'ANN-TMIN-PRBLST-T20FP30' : '30% probability date of last 20F occurrence or later',
	'ANN-TMIN-PRBLST-T20FP40' : '40% probability date of last 20F occurrence or later',
	'ANN-TMIN-PRBLST-T20FP50' : '50% probability date of last 20F occurrence or later',
	'ANN-TMIN-PRBLST-T20FP60' : '60% probability date of last 20F occurrence or later',
	'ANN-TMIN-PRBLST-T20FP70' : '70% probability date of last 20F occurrence or later',
	'ANN-TMIN-PRBLST-T20FP80' : '80% probability date of last 20F occurrence or later',
	'ANN-TMIN-PRBLST-T20FP90' : '90% probability date of last 20F occurrence or later',
	'ANN-TMIN-PRBLST-T24FP10' : '10% probability date of last 24F occurrence or later',
	'ANN-TMIN-PRBLST-T24FP20' : '20% probability date of last 24F occurrence or later',
	'ANN-TMIN-PRBLST-T24FP30' : '30% probability date of last 24F occurrence or later',
	'ANN-TMIN-PRBLST-T24FP40' : '40% probability date of last 24F occurrence or later',
	'ANN-TMIN-PRBLST-T24FP50' : '50% probability date of last 24F occurrence or later',
	'ANN-TMIN-PRBLST-T24FP60' : '60% probability date of last 24F occurrence or later',
	'ANN-TMIN-PRBLST-T24FP70' : '70% probability date of last 24F occurrence or later',
	'ANN-TMIN-PRBLST-T24FP80' : '80% probability date of last 24F occurrence or later',
	'ANN-TMIN-PRBLST-T24FP90' : '90% probability date of last 24F occurrence or later',
	'ANN-TMIN-PRBLST-T28FP10' : '10% probability date of last 28F occurrence or later',
	'ANN-TMIN-PRBLST-T28FP20' : '20% probability date of last 28F occurrence or later',
	'ANN-TMIN-PRBLST-T28FP30' : '30% probability date of last 28F occurrence or later',
	'ANN-TMIN-PRBLST-T28FP40' : '40% probability date of last 28F occurrence or later',
	'ANN-TMIN-PRBLST-T28FP50' : '50% probability date of last 28F occurrence or later',
	'ANN-TMIN-PRBLST-T28FP60' : '60% probability date of last 28F occurrence or later',
	'ANN-TMIN-PRBLST-T28FP70' : '70% probability date of last 28F occurrence or later',
	'ANN-TMIN-PRBLST-T28FP80' : '80% probability date of last 28F occurrence or later',
	'ANN-TMIN-PRBLST-T28FP90' : '90% probability date of last 28F occurrence or later',
	'ANN-TMIN-PRBLST-T32FP10' : '10% probability date of last 32F occurrence or later',
	'ANN-TMIN-PRBLST-T32FP20' : '20% probability date of last 32F occurrence or later',
	'ANN-TMIN-PRBLST-T32FP30' : '30% probability date of last 32F occurrence or later',
	'ANN-TMIN-PRBLST-T32FP40' : '40% probability date of last 32F occurrence or later',
	'ANN-TMIN-PRBLST-T32FP50' : '50% probability date of last 32F occurrence or later',
	'ANN-TMIN-PRBLST-T32FP60' : '60% probability date of last 32F occurrence or later',
	'ANN-TMIN-PRBLST-T32FP70' : '70% probability date of last 32F occurrence or later',
	'ANN-TMIN-PRBLST-T32FP80' : '80% probability date of last 32F occurrence or later',
	'ANN-TMIN-PRBLST-T32FP90' : '90% probability date of last 32F occurrence or later',
	'ANN-TMIN-PRBLST-T36FP10' : '10% probability date of last 36F occurrence or later',
	'ANN-TMIN-PRBLST-T36FP20' : '20% probability date of last 36F occurrence or later',
	'ANN-TMIN-PRBLST-T36FP30' : '30% probability date of last 36F occurrence or later',
	'ANN-TMIN-PRBLST-T36FP40' : '40% probability date of last 36F occurrence or later',
	'ANN-TMIN-PRBLST-T36FP50' : '50% probability date of last 36F occurrence or later',
	'ANN-TMIN-PRBLST-T36FP60' : '60% probability date of last 36F occurrence or later',
	'ANN-TMIN-PRBLST-T36FP70' : '70% probability date of last 36F occurrence or later',
	'ANN-TMIN-PRBLST-T36FP80' : '80% probability date of last 36F occurrence or later',
	'ANN-TMIN-PRBLST-T36FP90' : '90% probability date of last 36F occurrence or later',
	'ANN-TMIN-PRBOCC-LSTH016' : 'probability of 16F or below at least once in the year',
	'ANN-TMIN-PRBOCC-LSTH020' : 'probability of 20F or below at least once in the year',
	'ANN-TMIN-PRBOCC-LSTH024' : 'probability of 24F or below at least once in the year',
	'ANN-TMIN-PRBOCC-LSTH028' : 'probability of 28F or below at least once in the year',
	'ANN-TMIN-PRBOCC-LSTH032' : 'probability of 32F or below at least once in the year',
	'ANN-TMIN-PRBOCC-LSTH036' : 'probability of 36F or below at least once in the year',
	'DJF-CLDD-BASE45' : 'Long-term averages of winter cooling degree days with base 45F',
	'DJF-CLDD-BASE50' : 'Long-term averages of winter cooling degree days with base 50F',
	'DJF-CLDD-BASE55' : 'Long-term averages of winter cooling degree days with base 55F',
	'DJF-CLDD-BASE57' : 'Long-term averages of winter cooling degree days with base 57F',
	'DJF-CLDD-BASE60' : 'Long-term averages of winter cooling degree days with base 60F',
	'DJF-CLDD-BASE70' : 'Long-term averages of winter cooling degree days with base 70F',
	'DJF-CLDD-BASE72' : 'Long-term averages of winter cooling degree days with base 72F',
	'DJF-CLDD-NORMAL' : 'Long-term averages of winter cooling degree days with base 65F',
	'DJF-DUTR-NORMAL' : 'Long-term averages of winter diurnal temperature range',
	'DJF-GRDD-BASE40' : 'Long-term averages of winter growing degree days with base 40F',
	'DJF-GRDD-BASE45' : 'Long-term averages of winter growing degree days with base 45F',
	'DJF-GRDD-BASE50' : 'Long-term averages of winter growing degree days with base 50F',
	'DJF-GRDD-BASE55' : 'Long-term averages of winter growing degree days with base 55F',
	'DJF-GRDD-BASE57' : 'Long-term averages of winter growing degree days with base 57F',
	'DJF-GRDD-BASE60' : 'Long-term averages of winter growing degree days with base 60F',
	'DJF-GRDD-BASE65' : 'Long-term averages of winter growing degree days with base 65F',
	'DJF-GRDD-BASE70' : 'Long-term averages of winter growing degree days with base 70F',
	'DJF-GRDD-BASE72' : 'Long-term averages of winter growing degree days with base 72F',
	'DJF-GRDD-TB4886' : 'Long-term averages of winter growing degree days with truncated bases 48F and 86F',
	'DJF-GRDD-TB5086' : 'Long-term averages of winter growing degree days with truncated bases 50F and 86F',
	'DJF-HTDD-BASE40' : 'Long-term averages of winter heating degree days with base 40F',
	'DJF-HTDD-BASE45' : 'Long-term averages of winter heating degree days with base 45F',
	'DJF-HTDD-BASE50' : 'Long-term averages of winter heating degree days with base 50F',
	'DJF-HTDD-BASE55' : 'Long-term averages of winter heating degree days with base 55F',
	'DJF-HTDD-BASE57' : 'Long-term averages of winter heating degree days with base 57F',
	'DJF-HTDD-BASE60' : 'Long-term averages of winter heating degree days with base 60F',
	'DJF-HTDD-NORMAL' : 'Long-term averages of winter heating degree days with base 65F',
	'DJF-PRCP-AVGNDS-GE001HI' : 'Long-term averages of number of days during December-February with precipitation >= 0.01 inches',
	'DJF-PRCP-AVGNDS-GE010HI' : 'Long-term averages of number of days during December-February with precipitation >= 0.10 inches',
	'DJF-PRCP-AVGNDS-GE050HI' : 'Long-term averages of number of days during December-February with precipitation >= 0.50 inches',
	'DJF-PRCP-AVGNDS-GE100HI' : 'Long-term averages of number of days during December-February with precipitation >= 1.00 inches',
	'DJF-PRCP-NORMAL' : 'Long-term averages of seasonal precipitation totals forDecember-February',
	'DJF-SNOW-AVGNDS-GE001TI' : 'Long-term averages of number of days during December-February with snowfall >= 0.1 inches',
	'DJF-SNOW-AVGNDS-GE010TI' : 'Long-term averages of number of days during December-February with snowfall >= 1.0 inches',
	'DJF-SNOW-AVGNDS-GE030TI' : 'Long-term averages of number of days during December-February with snowfall >= 3.0 inches',
	'DJF-SNOW-AVGNDS-GE050TI' : 'Long-term averages of number of days during December-February with snowfall >= 5.0 inches',
	'DJF-SNOW-AVGNDS-GE100TI' : 'Long-term averages of number of days during December-February with snowfall >= 10.0 inches',
	'DJF-SNOW-NORMAL' : 'Long-term averages of seasonal snowfall totals for December-February',
	'DJF-SNWD-AVGNDS-GE001WI' : 'Long-term averages of number of days during December-February with snow depth >= 1 inch',
	'DJF-SNWD-AVGNDS-GE003WI' : 'Long-term averages of number of days during December-February with snow depth >= 3 inches',
	'DJF-SNWD-AVGNDS-GE005WI' : 'Long-term averages of number of days during December-February with snow depth >= 5 inches',
	'DJF-SNWD-AVGNDS-GE010WI' : 'Long-term averages of number of days during December-February with snow depth >= 10 inches',
	'DJF-TAVG-NORMAL' : 'Long-term averages of winter average temperature',
	'DJF-TMAX-AVGNDS-GRTH040' : 'Long-term average number of days per winter where tmax is greater than or equal to 40F',
	'DJF-TMAX-AVGNDS-GRTH050' : 'Long-term average number of days per winter where tmax is greater than or equal to 50F',
	'DJF-TMAX-AVGNDS-GRTH060' : 'Long-term average number of days per winter where tmax is greater than or equal to 60F',
	'DJF-TMAX-AVGNDS-GRTH070' : 'Long-term average number of days per winter where tmax is greater than or equal to 70F',
	'DJF-TMAX-AVGNDS-GRTH080' : 'Long-term average number of days per winter where tmax is greater than or equal to 80F',
	'DJF-TMAX-AVGNDS-GRTH090' : 'Long-term average number of days per winter where tmax is greater than or equal to 90F',
	'DJF-TMAX-AVGNDS-GRTH100' : 'Long-term average number of days per winter where tmax is greater than or equal to 100F',
	'DJF-TMAX-AVGNDS-LSTH032' : 'Long-term average number of days per winter where tmax is less than or equal to 32F',
	'DJF-TMAX-NORMAL' : 'Long-term averages of winter maximum temperature',
	'DJF-TMIN-AVGNDS-LSTH000' : 'Long-term average number of days per winter where tmin is less than or equal to 0F',
	'DJF-TMIN-AVGNDS-LSTH010' : 'Long-term average number of days per winter where tmin is less than or equal to 10F',
	'DJF-TMIN-AVGNDS-LSTH020' : 'Long-term average number of days per winter where tmin is less than or equal to 20F',
	'DJF-TMIN-AVGNDS-LSTH032' : 'Long-term average number of days per winter where tmin is less than or equal to 32F',
	'DJF-TMIN-AVGNDS-LSTH040' : 'Long-term average number of days per winter where tmin is less than or equal to 40F',
	'DJF-TMIN-AVGNDS-LSTH050' : 'Long-term average number of days per winter where tmin is less than or equal to 50F',
	'DJF-TMIN-AVGNDS-LSTH060' : 'Long-term average number of days per winter where tmin is less than or equal to 60F',
	'DJF-TMIN-AVGNDS-LSTH070' : 'Long-term average number of days per winter where tmin is less than or equal to 70F',
	'DJF-TMIN-NORMAL' : 'Long-term averages of winter minimum temperature',
	'JJA-CLDD-BASE45' : 'Long-term averages of summer cooling degree days with base 45F',
	'JJA-CLDD-BASE50' : 'Long-term averages of summer cooling degree days with base 50F',
	'JJA-CLDD-BASE55' : 'Long-term averages of summer cooling degree days with base 55F',
	'JJA-CLDD-BASE57' : 'Long-term averages of summer cooling degree days with base 57F',
	'JJA-CLDD-BASE60' : 'Long-term averages of summer cooling degree days with base 60F',
	'JJA-CLDD-BASE70' : 'Long-term averages of summer cooling degree days with base 70F',
	'JJA-CLDD-BASE72' : 'Long-term averages of summer cooling degree days with base 72F',
	'JJA-CLDD-NORMAL' : 'Long-term averages of summer cooling degree days with base 65F',
	'JJA-DUTR-NORMAL' : 'Long-term averages of summer diurnal temperature range',
	'JJA-GRDD-BASE40' : 'Long-term averages of summer growing degree days with base 40F',
	'JJA-GRDD-BASE45' : 'Long-term averages of summer growing degree days with base 45F',
	'JJA-GRDD-BASE50' : 'Long-term averages of summer growing degree days with base 50F',
	'JJA-GRDD-BASE55' : 'Long-term averages of summer growing degree days with base 55F',
	'JJA-GRDD-BASE57' : 'Long-term averages of summer growing degree days with base 57F',
	'JJA-GRDD-BASE60' : 'Long-term averages of summer growing degree days with base 60F',
	'JJA-GRDD-BASE65' : 'Long-term averages of summer growing degree days with base 65F',
	'JJA-GRDD-BASE70' : 'Long-term averages of summer growing degree days with base 70F',
	'JJA-GRDD-BASE72' : 'Long-term averages of summer growing degree days with base 72F',
	'JJA-GRDD-TB4886' : 'Long-term averages of summer growing degree days with truncated bases 48F and 86F',
	'JJA-GRDD-TB5086' : 'Long-term averages of summer growing degree days with truncated bases 50F and 86F',
	'JJA-HTDD-BASE40' : 'Long-term averages of summer heating degree days with base 40F',
	'JJA-HTDD-BASE45' : 'Long-term averages of summer heating degree days with base 45F',
	'JJA-HTDD-BASE50' : 'Long-term averages of summer heating degree days with base 50F',
	'JJA-HTDD-BASE55' : 'Long-term averages of summer heating degree days with base 55F',
	'JJA-HTDD-BASE57' : 'Long-term averages of summer heating degree days with base 57F',
	'JJA-HTDD-BASE60' : 'Long-term averages of summer heating degree days with base 60F',
	'JJA-HTDD-NORMAL' : 'Long-term averages of summer heating degree days with base 65F',
	'JJA-PRCP-AVGNDS-GE001HI' : 'Long-term averages of number of days during June-August with precipitation >= 0.01 inches',
	'JJA-PRCP-AVGNDS-GE010HI' : 'Long-term averages of number of days during June-August with precipitation >= 0.10 inches',
	'JJA-PRCP-AVGNDS-GE050HI' : 'Long-term averages of number of days during June-August with precipitation >= 0.50 inches',
	'JJA-PRCP-AVGNDS-GE100HI' : 'Long-term averages of number of days during June-August with precipitation >= 1.00 inches',
	'JJA-PRCP-NORMAL' : 'Long-term averages of seasonal precipitation totals for June-August',
	'JJA-SNOW-AVGNDS-GE001TI' : 'Long-term averages of number of days during June-August with snowfall >= 0.1 inches',
	'JJA-SNOW-AVGNDS-GE010TI' : 'Long-term averages of number of days during June-August with snowfall >= 1.0 inches',
	'JJA-SNOW-AVGNDS-GE030TI' : 'Long-term averages of number of days during June-August with snowfall >= 3.0 inches',
	'JJA-SNOW-AVGNDS-GE050TI' : 'Long-term averages of number of days during June-August with snowfall >= 5.0 inches',
	'JJA-SNOW-AVGNDS-GE100TI' : 'Long-term averages of number of days during June-August with snowfall >= 10.0 inches',
	'JJA-SNOW-NORMAL' : 'Long-term averages of seasonal snowfall totals for June-August',
	'JJA-SNWD-AVGNDS-GE001WI' : 'Long-term averages of number of days during June-August with snow depth >= 1 inch',
	'JJA-SNWD-AVGNDS-GE003WI' : 'Long-term averages of number of days during June-August with snow depth >= 3 inches',
	'JJA-SNWD-AVGNDS-GE005WI' : 'Long-term averages of number of days during June-August with snow depth >= 5 inches',
	'JJA-SNWD-AVGNDS-GE010WI' : 'Long-term averages of number of days during June-August with snow depth >= 10 inches',
	'JJA-TAVG-NORMAL' : 'Long-term averages of summer average temperature',
	'JJA-TMAX-AVGNDS-GRTH040' : 'Long-term average number of days per summer where tmax is greater than or equal to 40F',
	'JJA-TMAX-AVGNDS-GRTH050' : 'Long-term average number of days per summer where tmax is greater than or equal to 50F',
	'JJA-TMAX-AVGNDS-GRTH060' : 'Long-term average number of days per summer where tmax is greater than or equal to 60F',
	'JJA-TMAX-AVGNDS-GRTH070' : 'Long-term average number of days per summer where tmax is greater than or equal to 70F',
	'JJA-TMAX-AVGNDS-GRTH080' : 'Long-term average number of days per summer where tmax is greater than or equal to 80F',
	'JJA-TMAX-AVGNDS-GRTH090' : 'Long-term average number of days per summer where tmax is greater than or equal to 90F',
	'JJA-TMAX-AVGNDS-GRTH100' : 'Long-term average number of days per summer where tmax is greater than or equal to 100F',
	'JJA-TMAX-AVGNDS-LSTH032' : 'Long-term average number of days per summer where tmax is less than or equal to 32F',
	'JJA-TMAX-NORMAL' : 'Long-term averages of summer maximum temperature',
	'JJA-TMIN-AVGNDS-LSTH000' : 'Long-term average number of days per summer where tmin is less than or equal to 0F',
	'JJA-TMIN-AVGNDS-LSTH010' : 'Long-term average number of days per summer where tmin is less than or equal to 10F',
	'JJA-TMIN-AVGNDS-LSTH020' : 'Long-term average number of days per summer where tmin is less than or equal to 20F',
	'JJA-TMIN-AVGNDS-LSTH032' : 'Long-term average number of days per summer where tmin is less than or equal to 32F',
	'JJA-TMIN-AVGNDS-LSTH040' : 'Long-term average number of days per summer where tmin is less than or equal to 40F',
	'JJA-TMIN-AVGNDS-LSTH050' : 'Long-term average number of days per summer where tmin is less than or equal to 50F',
	'JJA-TMIN-AVGNDS-LSTH060' : 'Long-term average number of days per summer where tmin is less than or equal to 60F',
	'JJA-TMIN-AVGNDS-LSTH070' : 'Long-term average number of days per summer where tmin is less than or equal to 70F',
	'JJA-TMIN-NORMAL' : 'Long-term averages of summer minimum temperature',
	'MAM-CLDD-BASE45' : 'Long-term averages of spring cooling degree days with base 45F',
	'MAM-CLDD-BASE50' : 'Long-term averages of spring cooling degree days with base 50F',
	'MAM-CLDD-BASE55' : 'Long-term averages of spring cooling degree days with base 55F',
	'MAM-CLDD-BASE57' : 'Long-term averages of spring cooling degree days with base 57F',
	'MAM-CLDD-BASE60' : 'Long-term averages of spring cooling degree days with base 60F',
	'MAM-CLDD-BASE70' : 'Long-term averages of spring cooling degree days with base 70F',
	'MAM-CLDD-BASE72' : 'Long-term averages of spring cooling degree days with base 72F',
	'MAM-CLDD-NORMAL' : 'Long-term averages of spring cooling degree days with base 65F',
	'MAM-DUTR-NORMAL' : 'Long-term averages of spring diurnal temperature range',
	'MAM-GRDD-BASE40' : 'Long-term averages of spring growing degree days with base 40F',
	'MAM-GRDD-BASE45' : 'Long-term averages of spring growing degree days with base 45F',
	'MAM-GRDD-BASE50' : 'Long-term averages of spring growing degree days with base 50F',
	'MAM-GRDD-BASE55' : 'Long-term averages of spring growing degree days with base 55F',
	'MAM-GRDD-BASE57' : 'Long-term averages of spring growing degree days with base 57F',
	'MAM-GRDD-BASE60' : 'Long-term averages of spring growing degree days with base 60F',
	'MAM-GRDD-BASE65' : 'Long-term averages of spring growing degree days with base 65F',
	'MAM-GRDD-BASE70' : 'Long-term averages of spring growing degree days with base 70F',
	'MAM-GRDD-BASE72' : 'Long-term averages of spring growing degree days with base 72F',
	'MAM-GRDD-TB4886' : 'Long-term averages of summer growing degree days with truncated bases 48F and 86F',
	'MAM-GRDD-TB5086' : 'Long-term averages of summer growing degree days with truncated bases 50F and 86F',
	'MAM-HTDD-BASE40' : 'Long-term averages of spring heating degree days with base 40F',
	'MAM-HTDD-BASE45' : 'Long-term averages of spring heating degree days with base 45F',
	'MAM-HTDD-BASE50' : 'Long-term averages of spring heating degree days with base 50F',
	'MAM-HTDD-BASE55' : 'Long-term averages of spring heating degree days with base 55F',
	'MAM-HTDD-BASE57' : 'Long-term averages of spring heating degree days with base 57F',
	'MAM-HTDD-BASE60' : 'Long-term averages of spring heating degree days with base 60F',
	'MAM-HTDD-NORMAL' : 'Long-term averages of spring heating degree days with base 65F',
	'MAM-PRCP-AVGNDS-GE001HI' : 'Long-term averages of number of days during March-May with precipitation >= 0.01 inches',
	'MAM-PRCP-AVGNDS-GE010HI' : 'Long-term averages of number of days during March-May with precipitation >= a 0.10 inches',
	'MAM-PRCP-AVGNDS-GE050HI' : 'Long-term averages of number of days during March-May with precipitation >= 0.50 inches',
	'MAM-PRCP-AVGNDS-GE100HI' : 'Long-term averages of number of days during March-May with precipitation >= 1.00 inches',
	'MAM-PRCP-NORMAL' : 'Long-term averages of seasonal precipitation totals for March-May',
	'MAM-SNOW-AVGNDS-GE001TI' : 'Long-term averages of number of days during March-May with snowfall >= 0.1 inches',
	'MAM-SNOW-AVGNDS-GE010TI' : 'Long-term averages of number of days during March-May with snowfall >= 1.0 inches',
	'MAM-SNOW-AVGNDS-GE030TI' : 'Long-term averages of number of days during March-May with snowfall >= 3.0 inches',
	'MAM-SNOW-AVGNDS-GE050TI' : 'Long-term averages of number of days during March-May with snowfall >= 5.0 inches',
	'MAM-SNOW-AVGNDS-GE100TI' : 'Long-term averages of number of days during March-May with snowfall >= 10.0 inches',
	'MAM-SNOW-NORMAL' : 'Long-term averages of seasonal snowfall totals for March-May',
	'MAM-SNWD-AVGNDS-GE001WI' : 'Long-term averages of number of days during March-May with snow depth >= 1 inch',
	'MAM-SNWD-AVGNDS-GE003WI' : 'Long-term averages of number of days during March-May with snow depth >= 3 inches',
	'MAM-SNWD-AVGNDS-GE005WI' : 'Long-term averages of number of days during March-May with snow depth >= 5 inches',
	'MAM-SNWD-AVGNDS-GE010WI' : 'Long-term averages of number of days during March-May with snow depth >= 10 inches',
	'MAM-TAVG-NORMAL' : 'Long-term averages of spring average temperature',
	'MAM-TMAX-AVGNDS-GRTH040' : 'Long-term average number of days per spring where tmax is greater than or equal to 40F',
	'MAM-TMAX-AVGNDS-GRTH050' : 'Long-term average number of days per spring where tmax is greater than or equal to 50F',
	'MAM-TMAX-AVGNDS-GRTH060' : 'Long-term average number of days per spring where tmax is greater than or equal to 60F',
	'MAM-TMAX-AVGNDS-GRTH070' : 'Long-term average number of days per spring where tmax is greater than or equal to 70F',
	'MAM-TMAX-AVGNDS-GRTH080' : 'Long-term average number of days per spring where tmax is greater than or equal to 80F',
	'MAM-TMAX-AVGNDS-GRTH090' : 'Long-term average number of days per spring where tmax is greater than or equal to 90F',
	'MAM-TMAX-AVGNDS-GRTH100' : 'Long-term average number of days per spring where tmax is greater than or equal to 100F',
	'MAM-TMAX-AVGNDS-LSTH032' : 'Long-term average number of days per spring where tmax is less than or equal to 32F',
	'MAM-TMAX-NORMAL' : 'Long-term averages of spring maximum temperature',
	'MAM-TMIN-AVGNDS-LSTH000' : 'Long-term average number of days per spring where tmin is less than or equal to 0F',
	'MAM-TMIN-AVGNDS-LSTH010' : 'Long-term average number of days per spring where tmin is less than or equal to 10F',
	'MAM-TMIN-AVGNDS-LSTH020' : 'Long-term average number of days per spring where tmin is less than or equal to 20F',
	'MAM-TMIN-AVGNDS-LSTH032' : 'Long-term average number of days per spring where tmin is less than or equal to 32F',
	'MAM-TMIN-AVGNDS-LSTH040' : 'Long-term average number of days per spring where tmin is less than or equal to 40F',
	'MAM-TMIN-AVGNDS-LSTH050' : 'Long-term average number of days per spring where tmin is less than or equal to 50F',
	'MAM-TMIN-AVGNDS-LSTH060' : 'Long-term average number of days per spring where tmin is less than or equal to 60F',
	'MAM-TMIN-AVGNDS-LSTH070' : 'Long-term average number of days per spring where tmin is less than or equal to 70F',
	'MAM-TMIN-NORMAL' : 'Long-term averages of spring minimum temperature',
	'SON-CLDD-BASE45' : 'Long-term averages of autumn cooling degree days with base 45F',
	'SON-CLDD-BASE50' : 'Long-term averages of autumn cooling degree days with base 50F',
	'SON-CLDD-BASE55' : 'Long-term averages of autumn cooling degree days with base 55F',
	'SON-CLDD-BASE57' : 'Long-term averages of autumn cooling degree days with base 57F',
	'SON-CLDD-BASE60' : 'Long-term averages of autumn cooling degree days with base 60F',
	'SON-CLDD-BASE70' : 'Long-term averages of autumn cooling degree days with base 70F',
	'SON-CLDD-BASE72' : 'Long-term averages of autumn cooling degree days with base 72F',
	'SON-CLDD-NORMAL' : 'Long-term averages of autumn cooling degree days with base 65F',
	'SON-DUTR-NORMAL' : 'Long-term averages of autumn diurnal temperature range',
	'SON-GRDD-BASE40' : 'Long-term averages of fall growing degree days with base 40F',
	'SON-GRDD-BASE45' : 'Long-term averages of fall growing degree days with base 45F',
	'SON-GRDD-BASE50' : 'Long-term averages of fall growing degree days with base 50F',
	'SON-GRDD-BASE55' : 'Long-term averages of fall growing degree days with base 55F',
	'SON-GRDD-BASE57' : 'Long-term averages of fall growing degree days with base 57F',
	'SON-GRDD-BASE60' : 'Long-term averages of fall growing degree days with base 60F',
	'SON-GRDD-BASE65' : 'Long-term averages of fall growing degree days with base 65F',
	'SON-GRDD-BASE70' : 'Long-term averages of fall growing degree days with base 70F',
	'SON-GRDD-BASE72' : 'Long-term averages of fall growing degree days with base 72F',
	'SON-GRDD-TB4886' : 'Long-term averages of summer growing degree days with truncated bases 48F and 86F',
	'SON-GRDD-TB5086' : 'Long-term averages of summer growing degree days with truncated bases 50F and 86F',
	'SON-HTDD-BASE40' : 'Long-term averages of autumn heating degree days with base 40F',
	'SON-HTDD-BASE45' : 'Long-term averages of autumn heating degree days with base 45F',
	'SON-HTDD-BASE50' : 'Long-term averages of autumn heating degree days with base 50F',
	'SON-HTDD-BASE55' : 'Long-term averages of autumn heating degree days with base 55F',
	'SON-HTDD-BASE57' : 'Long-term averages of autumn heating degree days with base 57F',
	'SON-HTDD-BASE60' : 'Long-term averages of autumn heating degree days with base 60F',
	'SON-HTDD-NORMAL' : 'Long-term averages of autumn heating degree days with base 65F',
	'SON-PRCP-AVGNDS-GE001HI' : 'Long-term averages of number of days during September-November with precipitation >= 0.01 inches',
	'SON-PRCP-AVGNDS-GE010HI' : 'Long-term averages of number of days during September-November with precipitation >= 0.10 inches',
	'SON-PRCP-AVGNDS-GE050HI' : 'Long-term averages of number of days during September-November with precipitation >= 0.50 inches',
	'SON-PRCP-AVGNDS-GE100HI' : 'Long-term averages of number of days during September-November with precipitation >= 1.00 inches',
	'SON-PRCP-NORMAL' : 'Long-term averages of seasonal precipitation totals for September-November',
	'SON-SNOW-AVGNDS-GE001TI' : 'Long-term averages of number of days during September-November with snowfall >= 0.1 inches',
	'SON-SNOW-AVGNDS-GE010TI' : 'Long-term averages of number of days during September-November with snowfall >= 1.0 inches',
	'SON-SNOW-AVGNDS-GE030TI' : 'Long-term averages of number of days during September-November with snowfall >= 3.0 inches',
	'SON-SNOW-AVGNDS-GE050TI' : 'Long-term averages of number of days during September-November with snowfall >= 5.0 inches',
	'SON-SNOW-AVGNDS-GE100TI' : 'Long-term averages of number of days during September-November with snowfall >= 10.0 inches',
	'SON-SNOW-NORMAL' : 'Long-term averages of seasonal snowfall totals for September-November',
	'SON-SNWD-AVGNDS-GE001WI' : 'Long-term averages of number of days during September-November with snow depth >= 1 inch',
	'SON-SNWD-AVGNDS-GE003WI' : 'Long-term averages of number of days during September-November with snow depth >= 3 inches',
	'SON-SNWD-AVGNDS-GE005WI' : 'Long-term averages of number of days during September-November with snow depth >= 5 inches',
	'SON-SNWD-AVGNDS-GE010WI' : 'Long-term averages of number of days during September-November with snow depth >= 10 inches',
	'SON-TAVG-NORMAL' : 'Long-term averages of autumn average temperature',
	'SON-TMAX-AVGNDS-GRTH040' : 'Long-term average number of days per autumn where tmax is greater than or equal to 40F',
	'SON-TMAX-AVGNDS-GRTH050' : 'Long-term average number of days per autumn where tmax is greater than or equal to 50F',
	'SON-TMAX-AVGNDS-GRTH060' : 'Long-term average number of days per autumn where tmax is greater than or equal to 60F',
	'SON-TMAX-AVGNDS-GRTH070' : 'Long-term average number of days per autumn where tmax is greater than or equal to 70F',
	'SON-TMAX-AVGNDS-GRTH080' : 'Long-term average number of days per autumn where tmax is greater than or equal to 80F',
	'SON-TMAX-AVGNDS-GRTH090' : 'Long-term average number of days per autumn where tmax is greater than or equal to 90F',
	'SON-TMAX-AVGNDS-GRTH100' : 'Long-term average number of days per autumn where tmax is greater than or equal to 100F',
	'SON-TMAX-AVGNDS-LSTH032' : 'Long-term average number of days per autumn where tmax is less than or equal to 32F',
	'SON-TMAX-NORMAL' : 'Long-term averages of autumn maximum temperature',
	'SON-TMIN-AVGNDS-LSTH000' : 'Long-term average number of days per autumn where tmin is less than or equal to 0F',
	'SON-TMIN-AVGNDS-LSTH010' : 'Long-term average number of days per autumn where tmin is less than or equal to 10F',
	'SON-TMIN-AVGNDS-LSTH020' : 'Long-term average number of days per autumn where tmin is less than or equal to 20F',
	'SON-TMIN-AVGNDS-LSTH032' : 'Long-term average number of days per autumn where tmin is less than or equal to 32F',
	'SON-TMIN-AVGNDS-LSTH040' : 'Long-term average number of days per autumn where tmin is less than or equal to 40F',
	'SON-TMIN-AVGNDS-LSTH050' : 'Long-term average number of days per autumn where tmin is less than or equal to 50F',
	'SON-TMIN-AVGNDS-LSTH060' : 'Long-term average number of days per autumn where tmin is less than or equal to 60F',
	'SON-TMIN-AVGNDS-LSTH070' : 'Long-term average number of days per autumn where tmin is less than or equal to 70F',
	'SON-TMIN-NORMAL' : 'Long-term averages of autumn minimum temperature',



	// DATASET - NORMAL_DLY

	'DLY-CLDD-BASE45' : 'Long-term averages of daily cooling degree days with base 45F',
	'DLY-CLDD-BASE50' : 'Long-term averages of daily cooling degree days with base 50F',
	'DLY-CLDD-BASE55' : 'Long-term averages of daily cooling degree days with base 55F',
	'DLY-CLDD-BASE57' : 'Long-term averages of daily cooling degree days with base 57F',
	'DLY-CLDD-BASE60' : 'Long-term averages of daily cooling degree days with base 60F',
	'DLY-CLDD-BASE70' : 'Long-term averages of daily cooling degree days with base 70F',
	'DLY-CLDD-BASE72' : 'Long-term averages of daily cooling degree days with base 72F',
	'DLY-CLDD-NORMAL' : 'Long-term averages of daily cooling degree days with base 65F',
	'DLY-DUTR-NORMAL' : 'Long-term averages of daily diurnal temperature range',
	'DLY-DUTR-STDDEV' : 'Long-term standard deviations of daily diurnal temperature range',
	'DLY-GRDD-BASE40' : 'Long-term averages of daily growing degree days with base 40F',
	'DLY-GRDD-BASE45' : 'Long-term averages of daily growing degree days with base 45F',
	'DLY-GRDD-BASE50' : 'Long-term averages of daily growing degree days with base 50F',
	'DLY-GRDD-BASE55' : 'Long-term averages of daily growing degree days with base 55F',
	'DLY-GRDD-BASE57' : 'Long-term averages of daily growing degree days with base 57F',
	'DLY-GRDD-BASE60' : 'Long-term averages of daily growing degree days with base 60F',
	'DLY-GRDD-BASE65' : 'Long-term averages of daily growing degree days with base 65F',
	'DLY-GRDD-BASE70' : 'Long-term averages of daily growing degree days with base 70F',
	'DLY-GRDD-BASE72' : 'Long-term averages of daily growing degree days with base 72F',
	'DLY-GRDD-TB4886' : 'Long-term averages of daily growing degree days with truncated bases 48F and 86F',
	'DLY-GRDD-TB5086' : 'Long-term averages of daily growing degree days with truncated bases 50F and 86F',
	'DLY-HTDD-BASE40' : 'Long-term averages of daily heating degree days with base 40F',
	'DLY-HTDD-BASE45' : 'Long-term averages of daily heating degree days with base 45F',
	'DLY-HTDD-BASE50' : 'Long-term averages of daily heating degree days with base 50F',
	'DLY-HTDD-BASE55' : 'Long-term averages of daily heating degree days with base 55F',
	'DLY-HTDD-BASE57' : 'Long-term averages of daily heating degree days with base 57F',
	'DLY-HTDD-BASE60' : 'Long-term averages of daily heating degree days with base 60F',
	'DLY-HTDD-NORMAL' : 'Long-term averages of daily heating degree days with base 65F',
	'DLY-PRCP-25PCTL' : '25th percentiles of daily nonzero precipitation totals for 29-day windows centered on each day of the year',
	'DLY-PRCP-50PCTL' : '50th percentiles of daily nonzero precipitation totals for 29-day windows centered on each day of the year',
	'DLY-PRCP-75PCTL' : '75th percentiles of daily nonzero precipitation totals for 29-day windows centered on each day of the year',
	'DLY-PRCP-PCTALL-GE001HI' : 'Probability of precipitation >= 0.01 inches for 29-day windows centered on each day of the year',
	'DLY-PRCP-PCTALL-GE010HI' : 'Probability of precipitation >= 0.10 inches for 29-day windows centered on each day of the year',
	'DLY-PRCP-PCTALL-GE050HI' : 'Probability of precipitation >= 0.50 inches for 29-day windows centered on each day of the year',
	'DLY-PRCP-PCTALL-GE100HI' : 'Probability of precipitation >= 1.00 inches for 29-day windows centered on each day of the year',
	'DLY-SNOW-25PCTL' : '25th percentiles of daily nonzero snowfall totals for 29-day windows centered on each day of the year',
	'DLY-SNOW-50PCTL' : '50th percentiles of daily nonzero snowfall totals for 29-day windows centered on each day of the year',
	'DLY-SNOW-75PCTL' : '75th percentiles of daily nonzero snowfall totals for 29-day windows centered on each day of the year',
	'DLY-SNOW-PCTALL-GE001TI' : 'Probability of snowfall >= 0.1 inches for 29-day windows centered on each day of the year',
	'DLY-SNOW-PCTALL-GE010TI' : 'Probability of snowfall >= 1.0 inches for 29-day windows centered on each day of the year',
	'DLY-SNOW-PCTALL-GE030TI' : 'Probability of snowfall >= 3.0 inches for 29-day windows centered on each day of the year',
	'DLY-SNOW-PCTALL-GE050TI' : 'Probability of snowfall >= 5.0 inches for 29-day windows centered on each day of the year',
	'DLY-SNOW-PCTALL-GE100TI' : 'Probability of snowfall >= 10 inches for 29-day windows centered on each day of the year',
	'DLY-SNWD-25PCTL' : '25th percentiles of daily nonzero snow depth for 29-day windows centered on each day of the year',
	'DLY-SNWD-50PCTL' : '50th percentiles of daily nonzero snow depth for 29-day windows centered on each day of the year',
	'DLY-SNWD-75PCTL' : '75th percentiles of daily nonzero snow depth for 29-day windows centered on each day of the year',
	'DLY-SNWD-PCTALL-GE001WI' : 'Probability of snow depth >= 1 inch for 29-day windows centered on each day of the year',
	'DLY-SNWD-PCTALL-GE003WI' : 'Probability of snow depth >= 3 inches for 29-day windows centered on each day of the year',
	'DLY-SNWD-PCTALL-GE005WI' : 'Probability of snow depth >= 5 inches for 29-day windows centered on each day of the year',
	'DLY-SNWD-PCTALL-GE010WI' : 'Probability of snow depth >= 10 inches for 29-day windows centered on each day of the year',
	'DLY-TAVG-NORMAL' : 'Long-term averages of daily average temperature',
	'DLY-TAVG-STDDEV' : 'Long-term standard deviations of daily average temperature',
	'DLY-TMAX-NORMAL' : 'Long-term averages of daily maximum temperature',
	'DLY-TMAX-STDDEV' : 'Long-term standard deviations of daily maximum temperature',
	'DLY-TMIN-NORMAL' : 'Long-term averages of daily minimum temperature',
	'DLY-TMIN-STDDEV' : 'Long-term standard deviations of daily minimum temperature',
	'MTD-PRCP-NORMAL' : 'Long-term average month-to-date precipitation totals',
	'MTD-SNOW-NORMAL' : 'Long-term average month-to-date snowfall totals',
	'YTD-PRCP-NORMAL' : 'Long-term average year-to-date precipitation totals',
	'YTD-SNOW-NORMAL' : 'Long-term average year-to-date snowfall totals',


	// DATASET => NORMAL_MLY

	'MLY-CLDD-BASE45' : 'Long-term averages of monthly cooling degree days with base 45F',
	'MLY-CLDD-BASE50' : 'Long-term averages of monthly cooling degree days with base 50F',
	'MLY-CLDD-BASE55' : 'Long-term averages of monthly cooling degree days with base 55F',
	'MLY-CLDD-BASE57' : 'Long-term averages of monthly cooling degree days with base 57F',
	'MLY-CLDD-BASE60' : 'Long-term averages of monthly cooling degree days with base 60F',
	'MLY-CLDD-BASE70' : 'Long-term averages of monthly cooling degree days with base 70F',
	'MLY-CLDD-BASE72' : 'Long-term averages of monthly cooling degree days with base 72F',
	'MLY-CLDD-NORMAL' : 'Long-term averages of monthly cooling degree days with base 65F',
	'MLY-DUTR-NORMAL' : 'Long-term averages of monthly diurnal temperature range',
	'MLY-DUTR-STDDEV' : 'Long-term standard deviations of monthly diurnal temperature range',
	'MLY-GRDD-BASE40' : 'Long-term averages of monthly growing degree days with base 40F',
	'MLY-GRDD-BASE45' : 'Long-term averages of monthly growing degree days with base 45F',
	'MLY-GRDD-BASE50' : 'Long-term averages of monthly growing degree days with base 50F',
	'MLY-GRDD-BASE55' : 'Long-term averages of monthly growing degree days with base 55F',
	'MLY-GRDD-BASE57' : 'Long-term averages of monthly growing degree days with base 57F',
	'MLY-GRDD-BASE60' : 'Long-term averages of monthly growing degree days with base 60F',
	'MLY-GRDD-BASE65' : 'Long-term averages of monthly growing degree days with base 65F',
	'MLY-GRDD-BASE70' : 'Long-term averages of monthly growing degree days with base 70F',
	'MLY-GRDD-BASE72' : 'Long-term averages of monthly growing degree days with base 72F',
	'MLY-GRDD-TB4886' : 'Long-term averages of monthly growing degree days with truncated bases 48F and 86F',
	'MLY-GRDD-TB5086' : 'Long-term averages of monthly growing degree days with truncated bases 50F and 86F',
	'MLY-HTDD-BASE40' : 'Long-term averages of monthly heating degree days with base 40F',
	'MLY-HTDD-BASE45' : 'Long-term averages of monthly heating degree days with base 45F',
	'MLY-HTDD-BASE50' : 'Long-term averages of monthly heating degree days with base 50F',
	'MLY-HTDD-BASE55' : 'Long-term averages of monthly heating degree days with base 55F',
	'MLY-HTDD-BASE57' : 'Long-term averages of monthly heating degree days with base 57F',
	'MLY-HTDD-BASE60' : 'Long-term averages of monthly heating degree days with base 60F',
	'MLY-HTDD-NORMAL' : 'Long-term averages of monthly heating degree days with base 65F',
	'MLY-PRCP-25PCTL' : '25th percentiles of monthly precipitation totals',
	'MLY-PRCP-50PCTL' : '50th percentiles of monthly precipitation totals',
	'MLY-PRCP-75PCTL' : '75th percentiles of monthly precipitation totals',
	'MLY-PRCP-AVGNDS-GE001HI' : 'Long-term averages of number of days per month with precipitation >= 0.01 inches',
	'MLY-PRCP-AVGNDS-GE010HI' : 'Long-term averages of number of days per month with precipitation >= 0.10 inches',
	'MLY-PRCP-AVGNDS-GE050HI' : 'Long-term averages of number of days per month with precipitation >= 0.50 inches',
	'MLY-PRCP-AVGNDS-GE100HI' : 'Long-term averages of number of days per month with precipitation >= 1.00 inches',
	'MLY-PRCP-NORMAL' : 'Long-term averages of monthly precipitation totals',
	'MLY-SNOW-25PCTL' : '25th percentiles of monthly snowfall totals',
	'MLY-SNOW-50PCTL' : '50th percentiles of monthly snowfall totals',
	'MLY-SNOW-75PCTL' : '75th percentiles of monthly snowfall totals',
	'MLY-SNOW-AVGNDS-GE001TI' : 'Long-term averages of number of days per month with Snowfall >= 0.1 inches',
	'MLY-SNOW-AVGNDS-GE010TI' : 'Long-term averages of number of days per month with Snowfall >= 1.0 inches',
	'MLY-SNOW-AVGNDS-GE030TI' : 'Long-term averages of number of days per month with Snowfall >= 3.0 inches',
	'MLY-SNOW-AVGNDS-GE050TI' : 'Long-term averages of number of days per month with Snowfall >= 5.0 inches',
	'MLY-SNOW-AVGNDS-GE100TI' : 'Long-term averages of number of days per month with Snowfall >= 10.0 inches',
	'MLY-SNOW-NORMAL' : 'Long-term averages of monthly snowfall totals',
	'MLY-SNWD-AVGNDS-GE001WI' : 'Long-term averages of number of days per month with snow depth >= 1 inch',
	'MLY-SNWD-AVGNDS-GE003WI' : 'Long-term averages of number of days per month with snow depth >= 3 inches',
	'MLY-SNWD-AVGNDS-GE005WI' : 'Long-term averages of number of days per month with snow depth >= 5 inches',
	'MLY-SNWD-AVGNDS-GE010WI' : 'Long-term averages of number of days per month with snow depth >= 10 inches',
	'MLY-TAVG-NORMAL' : 'Long-term averages of monthly average temperature',
	'MLY-TAVG-STDDEV' : 'Long-term standard deviations of monthly average temperature',
	'MLY-TMAX-AVGNDS-GRTH040' : 'Long-term average number of days per month where tmax is greater than or equal to 40F',
	'MLY-TMAX-AVGNDS-GRTH050' : 'Long-term average number of days per month where tmax is greater than or equal to 50F',
	'MLY-TMAX-AVGNDS-GRTH060' : 'Long-term average number of days per month where tmax is greater than or equal to 60F',
	'MLY-TMAX-AVGNDS-GRTH070' : 'Long-term average number of days per month where tmax is greater than or equal to 70F',
	'MLY-TMAX-AVGNDS-GRTH080' : 'Long-term average number of days per month where tmax is greater than or equal to 80F',
	'MLY-TMAX-AVGNDS-GRTH090' : 'Long-term average number of days per month where tmax is greater than or equal to 90F',
	'MLY-TMAX-AVGNDS-GRTH100' : 'Long-term average number of days per month where tmax is greater than or equal to 100F',
	'MLY-TMAX-AVGNDS-LSTH032' : 'Long-term average number of days per month where tmax is less than or equal to 32F',
	'MLY-TMAX-NORMAL' : 'Long-term averages of monthly maximum temperature',
	'MLY-TMAX-STDDEV' : 'Long-term standard deviations of monthly maximum temperature',
	'MLY-TMIN-AVGNDS-LSTH000' : 'Long-term average number of days per month where tmin is less than or equal to 0F',
	'MLY-TMIN-AVGNDS-LSTH010' : 'Long-term average number of days per month where tmin is less than or equal to 10F',
	'MLY-TMIN-AVGNDS-LSTH020' : 'Long-term average number of days per month where tmin is less than or equal to 20F',
	'MLY-TMIN-AVGNDS-LSTH032' : 'Long-term average number of days per month where tmin is less than or equal to 32F',
	'MLY-TMIN-AVGNDS-LSTH040' : 'Long-term average number of days per month where tmin is less than or equal to 40F',
	'MLY-TMIN-AVGNDS-LSTH050' : 'Long-term average number of days per month where tmin is less than or equal to 50F',
	'MLY-TMIN-AVGNDS-LSTH060' : 'Long-term average number of days per month where tmin is less than or equal to 60F',
	'MLY-TMIN-AVGNDS-LSTH070' : 'Long-term average number of days per month where tmin is less than or equal to 70F',
	'MLY-TMIN-NORMAL' : 'Long-term averages of monthly minimum temperature',
	'MLY-TMIN-PRBOCC-LSTH016' : 'probability of 16F or below at least once in the month',
	'MLY-TMIN-PRBOCC-LSTH020' : 'probability of 20F or below at least once in the month',
	'MLY-TMIN-PRBOCC-LSTH024' : 'probability of 24F or below at least once in the month',
	'MLY-TMIN-PRBOCC-LSTH028' : 'probability of 28F or below at least once in the month',
	'MLY-TMIN-PRBOCC-LSTH032' : 'probability of 32F or below at least once in the month',
	'MLY-TMIN-PRBOCC-LSTH036' : 'probability of 36F or below at least once in the month',
	'MLY-TMIN-STDDEV' : 'Long-term standard deviations of monthly minimum temperature',

	// DATASET => PRECIP_15

	'QGAG' : 'Precipitation',
	'QPCP' : 'Precipitation',

	// DATASET => PRECIP_HLY

	'HPCP' : 'Precipitation'
};